### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by visaudi** [mayo/metalsmith-serve#4]
This may be totally silly, but I keep trying to serve to port 80 and when I do the app quits right away. I'm new to serving publicly, so this might just be me.

Thanks,

Ben

**Comment by mayo** [comment]
If you are on unix machine, you will need to be root to run on port 80, as it is a restricted port (or change security settings of your machine to allow unprivileged users to use port 80).

The other option is that something else is already running on port 80, or if your code isn't existing cleanly, the port/socket still could still be allocated to the process that has died.

Try running it on port higher than 1024 (8080, 8081, etc) and see if it works. From there you can decide which way to go.

**Comment by visaudi** [comment]
Mayo,

Do you think I should use a reverse proxy with metalsmith? I'm making my personal website and I'm trying to use this as an experience to become a better node programmer and server administrator. I want to make a healthy website ecosystem. I would also for learning purposes do everything with node. Is there a good node reverse proxy or should I just use nginx? I'm using a digital ocean droplet and am glad to buy another one for the reverse proxy. I want to do this simply and not poorly, so maybe I should be using a reverse proxy. What are you thoughts?

Thank you so much

**Comment by mayo** [comment]
Considering metalsmith is a static site generator, running a reverse proxy on a web server serving up a static site seems like an overkill, unless you have specific needs for it (SSL, security, load balancing, abstraction, etc). Personally, I would just use straight nginx (no proxying) to serve up a static site, if that. (I'd probably look toward Amazon's S3 + CloudFlare. You can get decent web hosting for few cents a month out of that setup.)

As a general setup, I'd be more inclined to use nginx for reverse proxy instead of various node.js modules (for eg. node-http-proxy), as it's proven and so far from my tests it performs better. It all depends on the requirements.
